# Generated by Django 4.1.3 on 2022-12-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
    ]
