# Generated by Django 4.1.3 on 2022-12-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointment_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='syptoms',
            field=models.TextField(blank=True),
        ),
    ]
