# Generated by Django 4.1.3 on 2022-12-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_appointment_syptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Apperence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timetaken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
