# Generated by Django 4.1.3 on 2022-12-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_appointment_apperence_appointment_timetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timetaken',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
