# Generated by Django 4.1.3 on 2022-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_appointment_timetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Apperence',
            field=models.BooleanField(default=False),
        ),
    ]
