# Generated by Django 4.1.3 on 2022-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Kardiolog', 'Kardiolog'), ('Skin DR', 'Skin DR'), ('Gastrolog', 'Gastrolog'), ('Eye DR', 'Eye DR'), ('Orolog', 'Orolog')], default='Doctor care', max_length=50),
        ),
    ]
