# Generated by Django 4.1.3 on 2022-12-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
